### ISSUE TITLE
yo elm-spa Failed on Windows 10

### ISSUE THREAD

**Issue by fontanajg** [jmfirth/generator-elm-spa#1]
I am on node v5.5 and npm v3.5.3.  Please see attached log for further detail.  Thank you.
[npm-debug.txt](https://github.com/jmfirth/generator-elm-spa/files/110248/npm-debug.txt)

**Comment by jmfirth** [comment]
You need to have elm installed which is best done globally through npm.

```
$ npm install -g elm
```
